### ISSUE TITLE
Detecting Compromising Photographs

### ISSUE THREAD

**Issue by ThatGuy65** [NCATComp410/comp410_fall_2023#16]
In the digital age, it is almost impossible to fully locate and know when your picture has been taken. Especially without your consent, these pictures can be used to transplant your face or likeness onto motives or causes you are either unaware of or don't support. by using facial recognition software, one could scour the web, (specifically places where photo sharing is rampant), and find how often your face pops up in those searches.

**Comment by claesmk** [comment]
This is a good goal but is definitely beyond the scope of what the primary library, [Presidio](https://microsoft.github.io/presidio/supported_entities/), we will be using for this class.  I would suggest taking a look at [face_recognize](https://pypi.org/project/face-recognition/) - this would likely be the best way to get you started.

**Comment by claesmk** [comment]
@ThatGuy65 as I previously mentioned you'll be looking at writing a completely new type of recognizer here.  I'd look over the links I sent.  I'd recommend writing an analyze_image() function and keep [analyze_text()](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L36) as-is for text based recognition.

**Comment by claesmk** [comment]
@ThatGuy65 I reverted #79 because it was causing too many issues for the rest of the class.  I'll get you some more detailed comments soon.  Don't worry about your assignment - I'll help you get it all squared away.

**Comment by claesmk** [comment]
This commit caused a couple of unintentional side effects which essentially made it impossible for the rest of the class to make progress with their individual PRs.  This is a great learning opportunity and everyone will benefit from this experience.

In general it's always best to get a code review from the most experienced individuals.  I would definitely have caught these problems and the whole situation could have been avoided by simply waiting for my review.  However, due to the deadline pressure, the merge happened before I had a chance to review it. 

Changing a requirements.txt file requires everyone who already has a codespace to install new requirements.  Everyone in the class would have needed a heads-up on this in order to understand the error messages.

One of the requirements, face_recognition, has an extremely long installation time which causes issues during codespace creation and when GitHub runs unit tests on each PR.  As more an more individuals pulled this commit into their workspaces, everything started slowing down significantly. 

Standard best-practice in situations like this is to revert the commit causing the issue.  I did take a quick look to see if there was a simple way to speed up the face_recognition installation time, however, that does not seem to be possible.  

Even before this issue, unit test execution time was increasing.  I wanted to wait until after this sprint to improve that, however, I decided to [merge](https://github.com/NCATComp410/comp410_fall_2023/pull/93) it now to help speed things up.  The downside of doing that was causing more merge conflicts and a code change which could cause more confusion.  Because the resulting merges were complicated, I resolved the merge conflicts for all the PRs that were in progress and also waived some of the merge requirements. 

Over the next few days I'll investigate how to best handle face_recognition so it doesn't cause any future problems.
