### ISSUE TITLE
Detect Credit Score 

### ISSUE THREAD

**Issue by rdouglas202** [NCATComp410/comp410_fall_2023#36]
Implement detection of a person's credit score as a numerical representation of their creditworthiness.

I will detect a 3-digit int which will range from 300-850 in order to know how well someone's credit is.

For example:
my current credit score is: XXX

**Comment by jewelworks** [comment]
Great idea Ryan! It would be a good idea to let the user know whether their credit is considered good or bad as well.

**Comment by claesmk** [comment]
A 3 digit number is not specific enough. You'll need to include context words such as "score" or "credit"

**Comment by Jordanwhit1** [comment]
Will this also be able to detect if the credit score is real or not? Occasionally ads will show a credit score but it will not actually be the persons credit score.

**Comment by claesmk** [comment]
> Will this also be able to detect if the credit score is real or not? Occasionally ads will show a credit score but it will not actually be the persons credit score.

Right @Jordanwhit1 this gets back to the point I was trying to make.  Pretend a hacker was able to exfil some data from a computer.  File 1 had the person's name.  File 2 had the credit score, for example
```
File-1
Name: John Jones
File -2
Credit Score: 700
```
You could probably conclude that John Jones has a credit score of 700.  The problem is credit scores change frequently.  

The more I think about this, the less I think this is PII, however, I'll allow this as long as there are clear context works that go with the 3-digit detection. @rdouglas202 please make sure the detection context words are clear in your description.

**Comment by rdouglas202** [comment]
> > Will this also be able to detect if the credit score is real or not? Occasionally ads will show a credit score but it will not actually be the persons credit score.
> 
> Right @Jordanwhit1 this gets back to the point I was trying to make. Pretend a hacker was able to exfil some data from a computer. File 1 had the person's name. File 2 had the credit score, for example
> 
> ```
> File-1
> Name: John Jones
> File -2
> Credit Score: 700
> ```
> 
> You could probably conclude that John Jones has a credit score of 700. The problem is credit scores change frequently.
> 
> The more I think about this, the less I think this is PII, however, I'll allow this as long as there are clear context works that go with the 3-digit detection. @rdouglas202 please make sure the detection context words are clear in your description.

@claesmk What if my example is not being detected by Microsoft Presidio? I'm currently not receiving a result from the spacy vs MS file.

**Comment by claesmk** [comment]
This is a good [example](https://microsoft.github.io/presidio/tutorial/06_context/) for what you'd need to add in analyze_text to detect a credit score.  A good place to add it is right after the [uuid_recognizer](https://github.com/NCATComp410/comp410_fall_2023/blob/dd0d4ed8c9f1bf930c96793e85ec0beb003e4c8d/pii_scan.py#L55C12-L55C12). 

You'd modify the zip code example to look for 3 digits instead of 5 and your context words would be credit and score.  The example includes regex code to look for a hyphenated zip code
```
r"(\b\d{5}(?:\-\d{4})?\b)"
```
you don't need all that - looking for 3 digits alone should do it
```
r"(\b\d{3}\b)"
```
