### ISSUE TITLE
Detect Marital Status

### ISSUE THREAD

**Issue by jenniferibe** [NCATComp410/comp410_fall_2023#39]
My project will focus on safeguarding marital status information, encompassing categories like being single, married, divorced, separated, or widowed. Marital status is extremely important in various facets of an individual's life, including legal, financial, and personal aspects. Ensuring the protection of this PII is crucial to preserving privacy, preventing potential exploitation, and upholding the integrity of legal and financial records.

Common ways to detect Marital Status:
1. Marriage Certificates
2. Census Surveys
3. Tax Returns
4. Employment Forms
5. Social Services Applications
6. Healthcare Records
7. Legal Documents

**Comment by claesmk** [comment]
@jenniferibe you have not accepted the invitation to join the team yet.  If you are having trouble with the email you should see it at the top of [this](https://github.com/orgs/NCATComp410/invitation) page.  You need to accept the invitation so that you have write access to the repo 

I'm not clear on how you plan to detect a password in text.  What will your detection steps be?

I also don't think a password is PII since they are typically hashed. None the less I'm OK with you continuing on this topic if you want.

**Comment by jenniferibe** [comment]
I just accepted the invitation, thank you! Also, after seeing your feedback, I will be changing my PII to something else.

**Comment by claesmk** [comment]
Description looks OK
